spring:
  h2:
    console:
      enabled: true
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

#  ssl:
#    bundle:
#      pem:
#        client:
#          truststore:
#            certificate: "classpath:certificate.pem"

server:
  port: 8081
